package main

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"ai-tutor/internal/app"
)

func TestCustomAssetHandler_NonHandledPath_PassesThrough(t *testing.T) {
	// Scenario 1: Nil app (before startup)
	handlerNil := customAssetHandler(nil)

	reqAssets := httptest.NewRequest(http.MethodGet, "/assets/index.js", nil)
	recAssets := httptest.NewRecorder()
	handlerNil.ServeHTTP(recAssets, reqAssets)

	if recAssets.Code != http.StatusOK || recAssets.Body.Len() > 0 {
		t.Fatalf("expected non-notebook path with nil app to pass through unhandled, got Code=%d, Body=%q", recAssets.Code, recAssets.Body.String())
	}

	// Scenario 2: App initialized but uploadDir is empty (uninitialized state)
	a := app.NewApp()
	handlerApp := customAssetHandler(a)

	reqIndex := httptest.NewRequest(http.MethodGet, "/index.html", nil)
	recIndex := httptest.NewRecorder()
	handlerApp.ServeHTTP(recIndex, reqIndex)

	if recIndex.Code != http.StatusOK || recIndex.Body.Len() > 0 {
		t.Fatalf("expected /index.html with empty uploadDir to pass through unhandled, got Code=%d, Body=%q", recIndex.Code, recIndex.Body.String())
	}
}

func TestCustomAssetHandler_NotebookPath_EmptyUploadDir_Returns503(t *testing.T) {
	handler := customAssetHandler(nil)

	req := httptest.NewRequest(http.MethodGet, "/notebooks/some-file.pdf", nil)
	rec := httptest.NewRecorder()

	handler.ServeHTTP(rec, req)

	if rec.Code != http.StatusServiceUnavailable {
		t.Fatalf("expected /notebooks/ path with uninitialized uploadDir to return 503 Service Unavailable, got status %d", rec.Code)
	}
}

func TestCustomAssetHandler_NotebookPath_ValidFile_ServesContent(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "notebook_test_*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tmpDir) }()

	dummyFile := filepath.Join(tmpDir, "test.pdf")
	if err := os.WriteFile(dummyFile, []byte("dummy pdf content"), 0644); err != nil {
		t.Fatalf("failed to write dummy file: %v", err)
	}

	_ = app.NewApp()

	handler := http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		fs := noDirListingFS{fs: http.Dir(tmpDir)}
		http.StripPrefix("/notebooks/", http.FileServer(fs)).ServeHTTP(rw, req)
	})

	req := httptest.NewRequest(http.MethodGet, "/notebooks/test.pdf", nil)
	rec := httptest.NewRecorder()

	handler.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200 OK serving valid notebook file, got %d", rec.Code)
	}
	if rec.Body.String() != "dummy pdf content" {
		t.Fatalf("expected body %q, got %q", "dummy pdf content", rec.Body.String())
	}
}

func TestCustomAssetHandler_NoteAssets_SpecialCharacters(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "notes_test_*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tmpDir) }()

	relFolder := "Learn Networking In 25 MINUTES [Crash Course] _ Networking Fundamentals + Cloud Networking Concepts/Pillar 1_nb-3b4f67a4-cf03-4111-9cb6-701c5257472a-ch-02/assets"
	assetFolder := filepath.Join(tmpDir, filepath.FromSlash(relFolder))
	if err := os.MkdirAll(assetFolder, 0755); err != nil {
		t.Fatalf("failed to create asset folder: %v", err)
	}

	dummyImage := filepath.Join(assetFolder, "screenshot_1791283565388_1791283565601.png")
	if err := os.WriteFile(dummyImage, []byte("fake png content"), 0644); err != nil {
		t.Fatalf("failed to write dummy image: %v", err)
	}

	t.Setenv("STUDYLOOP_NOTES_DIR", tmpDir)

	a := app.NewApp()
	handler := customAssetHandler(a)

	// Test with percent-encoded URL as generated by frontend
	reqPath := "/note-assets/Learn%20Networking%20In%2025%20MINUTES%20%5BCrash%20Course%5D%20_%20Networking%20Fundamentals%20%2B%20Cloud%20Networking%20Concepts/Pillar%201_nb-3b4f67a4-cf03-4111-9cb6-701c5257472a-ch-02/assets/screenshot_1791283565388_1791283565601.png"
	req := httptest.NewRequest(http.MethodGet, reqPath, nil)
	rec := httptest.NewRecorder()

	handler.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200 OK serving note asset, got %d. Body: %s", rec.Code, rec.Body.String())
	}
	if rec.Body.String() != "fake png content" {
		t.Fatalf("expected body 'fake png content', got %q", rec.Body.String())
	}
}

