// ponytail: single registry array; new pets and skins require zero template refactoring
export const PET_REGISTRY = [
  {
    id: 'cat',
    name: 'Mochi',
    title: 'Cozy Study Cat',
    description: 'A cozy feline companion who purrs and naps when you study.',
    isFree: true,
    priceCoins: 0,
    defaultSkin: 'calico',
    skins: [
      {
        id: 'calico',
        name: 'Calico (Classic)',
        primaryColor: '#F97316',
        secondaryColor: '#FFEDD5',
        accentColor: '#EA580C',
        isFree: true,
        priceCoins: 0,
      },
      {
        id: 'void',
        name: 'Void Black',
        primaryColor: '#1E293B',
        secondaryColor: '#475569',
        accentColor: '#0F172A',
        isFree: true,
        priceCoins: 0,
      },
      {
        id: 'matcha',
        name: 'Matcha Green',
        primaryColor: '#16A34A',
        secondaryColor: '#DCFCE7',
        accentColor: '#15803D',
        isFree: true,
        priceCoins: 0,
      },
      {
        id: 'lavender',
        name: 'Lavender Dusk',
        primaryColor: '#8B5CF6',
        secondaryColor: '#EDE9FE',
        accentColor: '#7C3AED',
        isFree: true,
        priceCoins: 0,
      },
    ],
    actions: ['idle', 'blink', 'coffee', 'wiggle', 'cheer', 'sleep'],
  },
  {
    id: 'dog',
    name: 'Buster',
    title: 'Loyal Study Pup',
    description: 'An enthusiastic pup who wags his floppy ears and keeps you motivated.',
    isFree: false,
    priceCoins: 1000,
    defaultSkin: 'golden',
    skins: [
      {
        id: 'golden',
        name: 'Golden Retriever',
        primaryColor: '#F59E0B',
        secondaryColor: '#FEF3C7',
        accentColor: '#D97706',
        isFree: true,
        priceCoins: 0,
      },
      {
        id: 'shiba',
        name: 'Shiba Inu',
        primaryColor: '#EA580C',
        secondaryColor: '#FFFFFF',
        accentColor: '#C2410C',
        isFree: false,
        priceCoins: 250,
      },
      {
        id: 'husky',
        name: 'Midnight Husky',
        primaryColor: '#334155',
        secondaryColor: '#F1F5F9',
        accentColor: '#0F172A',
        isFree: false,
        priceCoins: 500,
      },
    ],
    actions: ['idle', 'blink', 'coffee', 'wiggle', 'cheer', 'sleep'],
  },
  {
    id: 'dragon',
    name: 'Ignis',
    title: 'Mythic Ancient Dragon',
    description: 'A legendary dragon of ancient scholarship guarding your study focus.',
    isFree: false,
    priceCoins: 25000,
    defaultSkin: 'ruby',
    skins: [
      {
        id: 'ruby',
        name: 'Ruby Crimson',
        primaryColor: '#E11D48',
        secondaryColor: '#FFE4E6',
        accentColor: '#9F1239',
        isFree: true,
        priceCoins: 0,
      },
      {
        id: 'celestial',
        name: 'Celestial Gold',
        primaryColor: '#CA8A04',
        secondaryColor: '#FEF9C3',
        accentColor: '#854D0E',
        isFree: false,
        priceCoins: 5000,
      },
      {
        id: 'abyssal',
        name: 'Abyssal Void',
        primaryColor: '#6366F1',
        secondaryColor: '#312E81',
        accentColor: '#4338CA',
        isFree: false,
        priceCoins: 10000,
      },
    ],
    actions: ['idle', 'blink', 'coffee', 'wiggle', 'cheer', 'sleep'],
  },
]

export const PET_MESSAGES = [
  "You're doing great! Keep going!",
  'One flashcard at a time!',
  'Remember to stay hydrated!',
  'Focus mode active.',
  'Deep work pays off. Keep it up!',
  'Consistent practice beats cramming!',
  'Nice momentum! Stay locked in.',
]
